# Generated by Django 5.1.1 on 2024-11-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="owner",
        ),
    ]
