# Generated by Django 5.1.1 on 2024-10-26 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproductcount',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product'),
        ),
    ]
