# Generated by Django 5.1.1 on 2024-11-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_storeproductcount_store_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
