# Generated by Django 5.1.3 on 2024-11-24 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_product_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storeproductcount",
            old_name="product_name",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="storeproductcount",
            old_name="store_name",
            new_name="store",
        ),
    ]
