# Generated by Django 5.1.1 on 2024-10-26 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_storeproductcount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproductcount',
            name='price',
        ),
        migrations.AlterField(
            model_name='storeproductcount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
